### ISSUE TITLE
No interface.hpp

### ISSUE THREAD

**Issue by Quincunx271** [odinthenerd/abcd#5]
In [this commit](https://github.com/odinthenerd/abcd/commit/abd0642d24b073273b55bd227357232c6569584e), includes to **interface.hpp** were added, but no **interface.hpp** was added / existed beforehand. Thus, the library currently cannot work.

**Comment by odinthenerd** [comment]
wow #fail, thanks for the heads up!

**Comment by odinthenerd** [comment]
pushed some changes and fixed the issue. My unit tests for odinthenerd/format are now passing so I hope this is fixed. yell again if I broke something (sorry quite swamped right now)
